# Generated by Django 5.2.6 on 2025-09-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('en_sitio', models.BooleanField()),
                ('nombre', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=20)),
                ('torre', models.CharField(max_length=255)),
                ('incidente', models.CharField(max_length=255)),
                ('gestion', models.CharField(choices=[('SOPORTE', 'Soporte'), ('ASESORIA', 'Asesoría'), ('CIERRE', 'Cierre')], max_length=50)),
                ('observaciones', models.TextField()),
                ('plantilla', models.TextField()),
                ('login_n1', models.CharField(max_length=255)),
                ('tipo_servicio', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('observaciones_ultima', models.TextField()),
            ],
            options={
                'db_table': 'soporte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsesorSoporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asesor', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('login', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'asesor_soporte',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_funcionario', models.CharField(max_length=255, unique=True)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
    ]
