# Generated by Django 5.2.6 on 2025-09-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_despacho', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soporte',
            options={},
        ),
    ]
