# Generated by Django 5.2.6 on 2026-02-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_despacho', '0002_alter_soporte_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporte',
            name='gestion',
            field=models.CharField(choices=[('SOPORTE', 'Soporte'), ('ASESORIA', 'Asesoría'), ('CIERRE', 'Cierre'), ('ENRUTAR', 'Enrutar')], max_length=50),
        ),
    ]
