# Generated by Django 5.2.6 on 2026-02-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_despacho', '0003_alter_soporte_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorsoporte',
            name='estado',
            field=models.CharField(choices=[('NO_DISPONIBLE', 'No disponible'), ('EN_GESTION', 'En gestión'), ('EN_DESCANSO', 'En descanso'), ('CASO_COMPLEJO', 'Caso complejo')], default='NO_DISPONIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='asesorsoporte',
            name='perfil',
            field=models.CharField(choices=[('EN_CIERRES', 'En Cierres'), ('SOLO_SOPORTES', 'Solo Soportes'), ('TODO', 'Todo tipo de gestión')], default='TODO', max_length=20),
        ),
        migrations.AddField(
            model_name='asesorsoporte',
            name='ultimo_cambio_estado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
