# Generated by Django 5.2.6 on 2026-02-27 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_despacho', '0004_asesorsoporte_estado_asesorsoporte_perfil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.IntegerField(blank=True, null=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='api_despacho.asesorsoporte')),
            ],
            options={
                'db_table': 'historial_estado_asesor',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
