# Generated by Django 5.2.6 on 2026-03-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_despacho', '0005_historialestadoasesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='fecha_fin_gestion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soporte',
            name='fecha_inicio_gestion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soporte',
            name='segundos_gestion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
