# Generated by Django 5.2.6 on 2026-03-08 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_despacho', '0006_soporte_fecha_fin_gestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('soporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='api_despacho.soporte')),
            ],
            options={
                'db_table': 'chat_mensajes',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
