# Generated by Django 5.2.6 on 2026-03-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_despacho', '0007_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='chat_visto_despacho',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='soporte',
            name='chat_visto_soporte',
            field=models.BooleanField(default=True),
        ),
    ]
