# Generated by Django 5.2.6 on 2026-03-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_despacho', '0008_soporte_chat_visto_despacho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='soporte',
            name='chat_visto_tecnico',
            field=models.BooleanField(default=True),
        ),
    ]
