# Generated by Django 5.2.6 on 2026-03-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_despacho', '0009_funcionario_password_soporte_chat_visto_tecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soporte',
            name='fecha_fin_gestion',
        ),
        migrations.RemoveField(
            model_name='soporte',
            name='fecha_inicio_gestion',
        ),
        migrations.RemoveField(
            model_name='soporte',
            name='segundos_gestion',
        ),
        migrations.AlterField(
            model_name='soporte',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
