# Generated by Django 5.2.6 on 2026-03-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_despacho', '0010_remove_soporte_fecha_fin_gestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soporte',
            name='fecha_inicio_sitio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
