# Generated by Django 5.2.6 on 2026-03-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_despacho', '0011_soporte_fecha_fin_soporte_fecha_inicio_sitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
