# Generated by Django 5.2.6 on 2026-03-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_despacho', '0012_chatmessage_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='evidencias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
