# Generated by Django 5.2.6 on 2026-03-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_despacho', '0013_soporte_evidencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='prioridad',
            field=models.BooleanField(default=False),
        ),
    ]
