# Generated by Django 5.2.6 on 2026-03-22 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_despacho', '0015_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.CreateModel(
            name='SoporteEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('soporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_files', to='api_despacho.soporte')),
            ],
            options={
                'db_table': 'soporte_evidencias',
            },
        ),
    ]
